from app.tourism_amenitties.amenities.models.amenities import Amenity
from app.tourism_amenitties.destination.models.destination import Destination
from app.tourism_amenitties.attractions.models.attraction import Attraction
from app.tourism_amenitties.destination_translation.models.destination_translation import DestinationTranslation
from app.tourism_amenitties.attraction_translations.models.attraction_tran import AttractionTranslation
from app.tourism_amenitties.attraction_amenities.models.attraction_amenities import AttractionAmenity

# New Models
from app.tourism_amenitties.attractions.models.product_profile import TourismProductProfile
from app.tourism_amenitties.accommodation.models.accommodation import Accommodation, RoomType
from app.tourism_amenitties.events.models.event import Event
from app.tourism_amenitties.tours.models.tour_package import TourPackage
