"""add budget_amount to itinerary

Revision ID: ce35a23493d7
Revises: 9d4b2e7a31c8
Create Date: 2026-05-21 14:52:49.701477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce35a23493d7'
down_revision = '9d4b2e7a31c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_amount', sa.Float(), nullable=True, comment="Tourist's budget for the itinerary in KES or selected currency."))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_column('budget_amount')

    # ### end Alembic commands ###
