import geoalchemy2
"""Initial portable migration

Revision ID: e163bd036e80
Revises: 
Create Date: 2026-05-17 01:18:26.264983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e163bd036e80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('kiosk_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kiosk_session_transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kiosk_session_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment="Tourist's user account if known; null for anonymous walk-ups"),
    sa.Column('session_snapshot', sa.JSON(), nullable=True, comment='Immutable copy of kiosk_sessions.state at transfer creation time'),
    sa.Column('transfer_url', sa.Text(), nullable=False, comment='Public URL encoded in the QR: /api/sessions/transfer/<token>'),
    sa.Column('qr_image_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'redeemed', 'expired', 'revoked', name='transfer_status_enum'), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Hard expiry — 5 minutes from creation'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of successful phone scan'),
    sa.Column('mobile_ip', sa.String(length=45), nullable=True, comment='Phone IP on redemption — for audit'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_session_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_session_transfers_kiosk_session_id'), ['kiosk_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_session_transfers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_session_transfers_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_kiosk_session_transfers_user_id'), ['user_id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_webhook_events',
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_table('payments_mpesa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('payments_stripe',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_checkout_session_id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('transport_routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('origin_station_id', sa.Uuid(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['origin_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('destination_transport_routes',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('transport_route_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['transport_route_id'], ['transport_routes.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'transport_route_id')
    )
    op.create_table('transport_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numeric_id', sa.Integer(), nullable=False),
    sa.Column('transport_route_id', sa.Uuid(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transport_route_id'], ['transport_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_schedules_numeric_id'), ['numeric_id'], unique=True)

    op.create_table('kiosks',
    sa.Column('business_profile_id', sa.UUID(), nullable=True, comment='Business profile that owns/manages this kiosk'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name e.g. "JKIA Terminal 1A Kiosk"'),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True, comment="GPS point (PostGIS geography). Store as 'lat,lng' text if PostGIS unavailable."),
    sa.Column('address', sa.Text(), nullable=True, comment='Human-readable address for display'),
    sa.Column('location_type', sa.Enum('airport', 'sgr_station', 'hotel', 'national_park', 'museum', 'urban_centre', 'border_point', 'shopping_mall', name='kiosk_location_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'offline', 'maintenance', 'decommissioned', name='kiosk_status_enum'), server_default='offline', nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful ping from the kiosk agent'),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True, comment='Date the physical kiosk was deployed'),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True, comment='Set when status transitions to decommissioned'),
    sa.Column('configuration', postgresql.JSONB(astext_type=Text()), server_default='{}', nullable=True, comment='Per-kiosk runtime configuration overrides'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosks', schema=None) as batch_op:
        batch_op.create_index('idx_kiosks_location', ['location'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_kiosks_business_profile_id'), ['business_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosks_location_type'), ['location_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosks_status'), ['status'], unique=False)

    op.create_table('kiosk_content_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kiosk_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False, comment='Type of content in this cache entry'),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=False, comment='Cached content records ready for offline serving'),
    sa.Column('status', sa.Enum('current', 'stale', 'syncing', 'error', name='content_cache_status_enum'), server_default='stale', nullable=False),
    sa.Column('content_version', sa.String(length=64), nullable=True, comment='MD5/SHA hash of central content — used to detect staleness'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful sync with central content API'),
    sa.Column('synced_record_count', sa.Integer(), nullable=True, comment='Number of records in the current cache payload'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_content_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_content_cache_kiosk_id'), ['kiosk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_content_cache_status'), ['status'], unique=False)

    op.create_table('kiosk_health_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kiosk_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('heartbeat', 'startup', 'shutdown', 'crash', 'network_up', 'network_down', 'disk_warning', 'screen_on', 'screen_off', name='health_event_type_enum'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp of the health event'),
    sa.Column('metrics', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_health_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_health_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_health_logs_kiosk_id'), ['kiosk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_health_logs_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('kiosk_maintenance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kiosk_id', sa.UUID(), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True, comment='Admin/technician user who performed the maintenance'),
    sa.Column('maintenance_type', sa.Enum('software_update', 'hardware_repair', 'screen_cleaning', 'routine_check', 'content_refresh', 'network_change', 'decommission', name='maintenance_type_enum'), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_maintenance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_maintenance_logs_kiosk_id'), ['kiosk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_maintenance_logs_maintenance_type'), ['maintenance_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_maintenance_logs_performed_at'), ['performed_at'], unique=False)

    op.create_table('kiosk_sessions',
    sa.Column('kiosk_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Set if tourist logs in or links their account during the session'),
    sa.Column('session_token', sa.String(length=128), nullable=False, comment='Short-lived token for kiosk frontend API auth during the session'),
    sa.Column('status', sa.Enum('active', 'idle', 'transferred', 'completed', 'expired', name='kiosk_session_status_enum'), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(NOW())'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='Set when session is completed, transferred, or expired'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Kiosk LAN/WAN IP at session start'),
    sa.Column('device_info', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Kiosk hardware/software snapshot at session start. Shape: { os_version, app_version, screen_resolution, kiosk_model }'),
    sa.Column('state', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Live kiosk UI state snapshot; updated on each screen transition'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_sessions_kiosk_id'), ['kiosk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_sessions_session_token'), ['session_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_kiosk_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('kiosk_analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('kiosk_id', sa.UUID(), nullable=False, comment='Denormalised for fast dashboard queries without joining sessions'),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('screen', sa.String(length=80), nullable=True, comment='e.g. "home", "language_select", "itinerary_builder", "booking_confirm"'),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['kiosk_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_analytics_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_analytics_events_kiosk_id'), ['kiosk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_analytics_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_analytics_events_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('attraction_amenities', schema=None) as batch_op:
        batch_op.alter_column('attraction_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('amenity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('attraction_time_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('attraction_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('attraction_translations', schema=None) as batch_op:
        batch_op.alter_column('attraction_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('attractions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('destination_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('business_owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('booking_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('booking_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('target_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('kiosk_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('kiosk_session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('destination_translations', schema=None) as batch_op:
        batch_op.alter_column('destination_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('destination_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('itinerary_day_attractions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('itinerary_day_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('attraction_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('itinerary_days', schema=None) as batch_op:
        batch_op.alter_column('itinerary_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('media_gallery', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('target_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('tourist_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('target_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('user_trip_preferences', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trip_preferences', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('tourist_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('target_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('media_gallery', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('itinerary_days', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('itinerary_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('itinerary_day_attractions', schema=None) as batch_op:
        batch_op.alter_column('attraction_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('itinerary_day_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.alter_column('destination_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('destination_translations', schema=None) as batch_op:
        batch_op.alter_column('destination_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('kiosk_session_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('kiosk_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('booking_items', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('booking_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('attractions', schema=None) as batch_op:
        batch_op.alter_column('business_owner_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('destination_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('attraction_translations', schema=None) as batch_op:
        batch_op.alter_column('attraction_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('attraction_time_data', schema=None) as batch_op:
        batch_op.alter_column('attraction_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('attraction_amenities', schema=None) as batch_op:
        batch_op.alter_column('amenity_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('attraction_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('kiosk_analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_analytics_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_kiosk_analytics_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_kiosk_analytics_events_kiosk_id'))
        batch_op.drop_index(batch_op.f('ix_kiosk_analytics_events_event_type'))

    op.drop_table('kiosk_analytics_events')
    with op.batch_alter_table('kiosk_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_kiosk_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_kiosk_sessions_session_token'))
        batch_op.drop_index(batch_op.f('ix_kiosk_sessions_kiosk_id'))

    op.drop_table('kiosk_sessions')
    with op.batch_alter_table('kiosk_maintenance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_maintenance_logs_performed_at'))
        batch_op.drop_index(batch_op.f('ix_kiosk_maintenance_logs_maintenance_type'))
        batch_op.drop_index(batch_op.f('ix_kiosk_maintenance_logs_kiosk_id'))

    op.drop_table('kiosk_maintenance_logs')
    with op.batch_alter_table('kiosk_health_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_health_logs_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_kiosk_health_logs_kiosk_id'))
        batch_op.drop_index(batch_op.f('ix_kiosk_health_logs_event_type'))

    op.drop_table('kiosk_health_logs')
    with op.batch_alter_table('kiosk_content_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_content_cache_status'))
        batch_op.drop_index(batch_op.f('ix_kiosk_content_cache_kiosk_id'))

    op.drop_table('kiosk_content_cache')
    with op.batch_alter_table('kiosks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosks_status'))
        batch_op.drop_index(batch_op.f('ix_kiosks_location_type'))
        batch_op.drop_index(batch_op.f('ix_kiosks_business_profile_id'))
        batch_op.drop_index('idx_kiosks_location', postgresql_using='gist')

    op.drop_table('kiosks')
    with op.batch_alter_table('transport_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_schedules_numeric_id'))

    op.drop_table('transport_schedules')
    op.drop_table('destination_transport_routes')
    op.drop_table('user_roles')
    op.drop_table('transport_routes')
    op.drop_table('role_permissions')
    op.drop_table('payments_stripe')
    op.drop_table('payments_mpesa')
    op.drop_table('stripe_webhook_events')
    op.drop_table('stations')
    op.drop_table('roles')
    op.drop_table('permissions')
    with op.batch_alter_table('kiosk_session_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_session_transfers_user_id'))
        batch_op.drop_index(batch_op.f('ix_kiosk_session_transfers_token'))
        batch_op.drop_index(batch_op.f('ix_kiosk_session_transfers_status'))
        batch_op.drop_index(batch_op.f('ix_kiosk_session_transfers_kiosk_session_id'))

    op.drop_table('kiosk_session_transfers')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
